baseURL = 'https://chanpolo.netlify.app/'
defaultContentLanguage = 'fr'
languageCode = "fr-fr"
title = "Les Recettes de Chan et Polo"

enableRobotsTXT = true
pagerSize = 12

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[taxonomies]
  
  category = "categories"


[menu]
  [[menu.main]]
    identifier = "accueil"
    name = "Accueil"
    url = "/"
    weight = 1
    
  [[menu.main]]
    identifier = "recette"
    name = "Recettes"
    url = "#"
    weight = 10
  [[menu.main]]
    identifier = "recette-date"
    name = "Par Dates"
    url = "/recette"
    parent = "recette"
    weight = 10
  [[menu.main]]
    identifier = "recette-auteur"
    name = "Par Auteurs"
    url = "/recette-author"
    parent = "recette"
    weight = 30
  [[menu.main]]
    identifier = "recette-nom"
    name = "Par Noms"
    url = "/recette-name"
    parent = "recette"
    weight = 20

  [[menu.main]]
    identifier = "auteurs"
    name = "Auteurs"
    url = "#"
    weight = 60
  [[menu.main]]
    identifier = "recette-chan-polo"
    name = "Chan & Polo"
    url = "/auteur-chan-et-polo"
    parent = "auteurs"
    weight = 10
  [[menu.main]]
    identifier = "recette-jean"
    name = "Jean"
    url = "/auteur-jean"
    parent = "auteurs"
    weight = 20  
  [[menu.main]]
    identifier = "recette-paul"
    name = "Paul"
    url = "/auteur-paul"
    parent = "auteurs"
    weight = 70     
  [[menu.main]]
    identifier = "recette-foufy"
    name = "Foufy"
    url = "/auteur-foufy"
    parent = "auteurs"
    weight = 15     



  [[menu.main]]
    identifier = "type"
    name = "Types"
    url = "#"
    weight = 60
  [[menu.main]]
    identifier = "type-entree"
    name = "Entrées"
    url = "/type-entree"
    parent = "type"
    weight = 10
  [[menu.main]]
    identifier = "type-plat"
    name = "Plats"
    url = "/type-plat"
    parent = "type"
    weight = 20  
  [[menu.main]]
    identifier = "type-dessert"
    name = "Desserts"
    url = "/type-dessert"
    parent = "type"
    weight = 30     
  [[menu.main]]
    identifier = "type-base"
    name = "Bases"
    url = "/type-base"
    parent = "type"
    weight = 40 
  [[menu.main]]
    identifier = "type-aperitif"
    name = "Apéritifs"
    url = "/type-aperitif"
    parent = "type"
    weight = 50     

  [[menu.main]]
    identifier = "asie"
    name = "Asie"
    url = "/asie"
    weight = 70     

  [[menu.main]]
    identifier = "indexes"
    name = "Indexes"
    url = "#"
    weight = 90
  [[menu.main]]
    identifier = "index-global"
    name = "Global"
    url = "/index-global"
    parent = "indexes"
    weight = 10
  [[menu.main]]
    identifier = "index-recette"
    name = "Recettes"
    url = "/index-recette"
    parent = "indexes"
    weight = 30
  [[menu.main]]
    identifier = "index-asie"
    name = "Asie"
    url = "/index-asie"
    parent = "indexes"
    weight = 50



[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "titleshort", "summary", "date", "permalink"]
params = ["categories", "tags", "description"]

[outputs]
home = ["HTML", "RSS", "Algolia", "dessert", "entree", "plat", "genimages"]

[mediaTypes."application/json"]
  suffixes = ["json"]

[outputFormats]  
  [outputFormats.Entree]
    mediaType = "application/json"
    baseName = "json/entree" 
    isPlainText = true
  
  [outputFormats.Plat]
    mediaType = "application/json"
    baseName = "json/plat" 
    isPlainText = true

  [outputFormats.Dessert]
    mediaType = "application/json"
    baseName = "json/dessert" 
    isPlainText = true

  [outputFormats.Genimages]
    mediaType = "application/json"
    baseName = "json/genimages" 
    isPlainText = true

